language: node_js
node_js:
  - lts/* #设置语言版本
branches:
  only:
    - develop #设置只监听哪个分支
cache:
  apt: true
  yarn: true
  directories: 
    - node_modules #缓存依赖
install:  # 安装依赖
  - yarn
before_script: #构建生命周期的“钩子”
  - chmod 777 ./deploy.sh
script:
    - sh ./deploy.sh

